resource_type_general_values:
  - Audiovisual
  - Award
  - Book
  - BookChapter
  - Collection
  - ComputationalNotebook
  - ConferencePaper
  - ConferenceProceeding
  - DataPaper
  - Dataset
  - Dissertation
  - Event
  - Image
  - InteractiveResource
  - Instrument
  - Journal
  - JournalArticle
  - Model
  - OutputManagementPlan
  - PeerReview
  - PhysicalObject
  - Preprint
  - Project
  - Report
  - Service
  - Software
  - Sound
  - Standard
  - StudyRegistration
  - Text
  - Workflow
  - Other